# OpenCVFaceID/config/config.yaml

# --- File Paths ---
known_faces_dir: "../known_faces"
models_dir: "models"
database_dir: "../database"
db_file: "known_face_encodings.pkl"

# --- Camera Settings ---
camera_index: 0

# --- Processing Settings ---
# Face Detection Model (OpenCV DNN Caffe ResNet10-SSD)
detector:
  # Using user-provided relative paths
  prototxt_path: "../models/detection/deploy.prototxt"
  model_path: "../models/detection/res10_300x300_ssd_iter_140000.caffemodel"
  confidence_threshold: 0.5
  input_width: 300
  input_height: 300
  mean_subtraction: [104.0, 177.0, 123.0]

# --- Face Recognition Model (ONNX) --- ADD THIS SECTION ---
recognizer:
  # Using relative path, adjust if needed based on where you run from
  model_path: "../models/recognition/face_recognition_sface_2021dec.onnx"
  # Input size expected by this specific ONNX model
  input_width: 112
  input_height: 112
  # Preprocessing: Does the model expect BGR or RGB? Scale factor?
  # Common for many ONNX face models: Input is BGR, scaled 0-1 or similar. Check model specifics.
  scale_factor: 0.00392156862745098 # Example: Scale pixel values to 0-1 range
  swap_rb: False # Keep BGR if model expects BGR

# Threshold for face matching (lower distance = better match) - Needs tuning!
recognition_threshold_distance: 0.6

# --- UI Settings ---
display_window_name: "OpenCVFaceID - Live Recognition"
unknown_person_label: "Unknown"
box_color: [0, 255, 0] # Green